### ISSUE TITLE
Can't get attribute 'EBMPreprocessor' on <module 'interpret.glassbox.ebm.ebm'

### ISSUE THREAD

**Issue by KuechlerO** [gagneurlab/absplice#6]
Hey guys, your tool looks really interesting to me! :)
And so I wanted to give it a try.

However, I stumbled over this error when running the example on my Linux-server.
Do you know how to get around it?

```
[Sat Dec 24 01:35:02 2022]
rule absplice_dna:
    input: mmsplice_splicemap.csv, spliceai.vcf
    output: absplice_dna.csv
    jobid: 1
    reason: Missing output files: absplice_dna.csv; Input files updated by another job: mmsplice_splicemap.csv
    resources: tmpdir=/tmp

2022-12-24 01:35:06.874355: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/home/mi/olivek95/git_projects/absplice/example/.snakemake/scripts/tmp5a1c9dig.absplice_dna.py", line 11, in <module>
    splicing_result.predict_absplice_dna()
  File "/home/mi/olivek95/git_projects/absplice/absplice/result.py", line 568, in predict_absplice_dna
    model = pickle.load(open(pickle_file, 'rb'))
AttributeError: Can't get attribute 'EBMPreprocessor' on <module 'interpret.glassbox.ebm.ebm' from '/buffer/ag_bsc/PS_SEQAN_STUDENTS/olivek95/miniconda3/envs/absplice/lib/python3.9/site-packages/interpret/glassbox/ebm/ebm.py'>
[Sat Dec 24 01:35:17 2022]
Error in rule absplice_dna:
    jobid: 1
    input: mmsplice_splicemap.csv, spliceai.vcf
    output: absplice_dna.csv

RuleException:
CalledProcessError in file /home/mi/olivek95/git_projects/absplice/example/Snakefile, line 88:
Command 'set -euo pipefail;  /buffer/ag_bsc/PS_SEQAN_STUDENTS/olivek95/miniconda3/envs/absplice/bin/python /home/mi/olivek95/git_projects/absplice/example/.snakemake/scripts/tmp5a1c9dig.absplice_dna.py' returned non-zero exit status 1.
  File "/home/mi/olivek95/git_projects/absplice/example/Snakefile", line 88, in __rule_absplice_dna
  File "/buffer/ag_bsc/PS_SEQAN_STUDENTS/olivek95/miniconda3/envs/absplice/lib/python3.9/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2022-12-24T013405.664404.snakemake.log
```

Initial command:
`cd example; python -m snakemake -j 1`

**Comment by WagnerNils** [comment]
Hi, sorry for the late reply. We updated the repository and fixed dependencies in the conda environment. I hope that this also fixes this error. Can you check if it works for you now?
